server: "hub.lambdatest.com"
user: "LT_USERNAME"
key: "LT_ACCESS_KEY"

common_caps:
  "build": "RSpec Selenium Demo"
  "visual": false
  "network": false
  "console": false

browser_caps:
  -
    "browserName": "chrome"
    "version": "latest"
    "platform": "windows 10"
  -
    "browserName": "firefox"
    "version": "latest"
    "platform": "windows 7"
  -
    "browserName": "internet explorer"
    "version": "latest"
    "platform": "windows 10"
  -
    "browserName": "safari"
    "version": "latest"
    "platform": "macOS High Sierra"
